### PR TITLE
Enable sessions on existing servers (fixes #30)

### LINKED ISSUE #30: Tests fail for instantiated app
The fix in #29 broke tests that create sessions around an existing instance of an app.

> app, in my case, is an Object and not a Function. I already have a full working server, but I still need to extract the url from the app object itself.

HT @XVincentX

### PR DESCRIPTION
**Pull request by rjz**

### CODE REVIEW

**Comment by rjz** [comment]
@XVincentX: would you be willing to point your dependencies at `github.com/rjz/supertest-session#cc11bbf` and confirm this fixes #30? Looking forward to getting this merged.

**Comment by XVincentX** [comment]
Hold on! Doing it right now.

**Comment by XVincentX** [comment]
@rjz

image

ROAR! Let's release this!

**Comment by rjz** [comment]
Thanks, @XVincentX! supertest-session@3.1.2 is out to npm.

**Pull request merged**
