### PR TITLE
Upgrade to newer version of supertest

### PR DESCRIPTION
**Pull request by steebchen**
Upgrade to a newer version of supertest to fix double callback bug when using promises.

### CODE REVIEW

**Comment by rjz** [comment]
Thanks, @steebchen—looking forward to getting this merged up! For others' reference, could you link up the bug in question (or add a regression test to show the fix)?

**Comment by steebchen** [comment]
I don't have a code example since I used it in a big project, but upgrading to this version fixed the bug when returning multiple promises in chained .then()s. The warning which gets printed says "superagent: double callback bug. Upgrade to v3.2+ to fix this". I know that supertest^2 doesn't come with superagent^3.2, but the warning disappeared so I think that another code change fixed that. Not the best explanation, I know, but the upgrade did fix the warning for me.

**Comment by rjz** [comment]
Got it, and good to keep the dependencies updated in any case! Thanks again for taking care of this, @steebchen.

**Comment by rjz** [comment]
Published to npm as version 3.0.0.

**Pull request merged**
